add old nodejs images to support 4.1,4.2 and 3.11
openshift/odo-init-image pull request #54
Opened 2020-03-30 10:40 UTC by girishramnani

we need to use older nodejs image for supporting 4.1, 4.2 and 3.11

2020-03-30 13:41 UTC, cdrage requested changes
Just curious, what was the point of removing them in the first place, technically they're now outdated / not supported? Or should we still support them?

2020-04-02 13:20 UTC, girishramnani commented
They have been deprecated/removed but it seems the catalog on older clusters don’t seem to get updated that often

2020-04-02 14:28 UTC, kadel commented
> Just curious, what was the point of removing them in the first place, technically they're now outdated / not supported? Or should we still support them?

they have been deprecated for 4.x but older versions they are still present, they are not supported, but they can be used.

2020-04-02 16:52 UTC, kadel commented
/refresh

2020-04-02 16:53 UTC, kadel commented
/approve

2020-04-02 16:57 UTC, cdrage commented
/lgtm

2020-04-02 16:57 UTC, cdrage approved these changes
/lgtm

2020-04-02 17:03 UTC, merged